### ISSUE TITLE
 Abbotton\DouDian\Api\BaseRequest::getAccessToken 报错了

### ISSUE THREAD

**Issue by pifeifei** [Abbotton/laravel-doudian#16]
API不存在或API已下线

https://op.jinritemai.com/docs/api-docs/162/1600

**Comment by pifeifei** [comment]
我看  dev-main 里面已经更新了，是有什么问题吗？没有发布新版本？   v1.1.6 ?

**Comment by Abbotton** [comment]
不好意思，最近比较忙，今晚我抽时间同步一下，然后发一版。感谢支持。

**Comment by Abbotton** [comment]
@pifeifei 再试一下，刚发了新版。
